version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sample-web:
    image: sample-web:latest
    container_name: sample-web
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  backend: