spring:
  application:
    name: sample-web
  datasource:
    url: jdbc:postgresql://postgres:5432/my_database
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true